import "../globals.css";
import type { Metadata } from "next";

//shadcn uis
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/components/footer";
import MainMenu from "@/components/main-menu";

import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Kai The Developer",
  description: "Generated by Next.14 + Sanity",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <header className="flex items-center justify-between"></header> */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header>
            <MainMenu />
          </header>
          <main className="flex min-h-screen flex-col items-center">
            {children}
          </main>
          <Toaster />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
